
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-5pm-3
owner: ucsb-cs156-f23
repo_name: team02-f23-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBX3Xdg","is_bot":false,"login":"kaitntom","name":""},"headRefName":"Kaitlyn-Org-Put","number":69,"title":"Kaitlyn - finished put and finished put tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-3/pull/69"},{"author":{"id":"U_kgDOBqGjHg","is_bot":false,"login":"madisonlong1","name":""},"headRefName":"Madison-MenuItemReview","number":63,"title":"Madison menu item review","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-3/pull/63"},{"author":{"id":"U_kgDOBmv1pg","is_bot":false,"login":"livjono","name":"Olivia Jonokuchi"},"headRefName":"liv-HelpRequest-controller-get-show","number":59,"title":"Liv - add GET(show) endpoint and tests for a single record in HelpRequest table","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-3/pull/59"},{"author":{"id":"U_kgDOBmv1pg","is_bot":false,"login":"livjono","name":"Olivia Jonokuchi"},"headRefName":"liv-README","number":52,"title":"Liv updated README with links to the prod and qa instances on dokku","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-3/pull/52"}]
